-- Code Generated by Sidekick is for learning and experimentation purposes only.
-- filename: sql/create_streaming_table.sql
-- ─────────────────────────────────────────────────────────────────────
--  PURPOSE : Creates Bronze streaming table reading from ADLS Gen2
--  LAYER   : Bronze (raw / landing zone)
--  RUN IN  : Databricks ETL Pipeline (Delta Live Tables) ONLY
--  TRIGGER : Triggered mode — runs on demand
-- ─────────────────────────────────────────────────────────────────────

CREATE OR REFRESH STREAMING TABLE stream_bronze.orders_bronze
COMMENT "Bronze: raw orders ingested from ADLS Gen2 via Auto Loader"
TBLPROPERTIES (
  "quality"       = "bronze",
  "layer"         = "medallion",
  "source_system" = "OMS",
  "table_owner"         = "data-engineering"
)
AS
SELECT

  -- ── Core order identity ───────────────────────────────────────────
  order_id,
  customer_id,
  customer_name,

  -- ── Order details ─────────────────────────────────────────────────
  order_date,
  store_id,
  channel,
  status,
  currency,
  total_amount,

  -- ── Nested fields (kept as-is in bronze — no transformation) ──────
  items,
  shipping_address,

  -- ── Lineage metadata — where did this record come from? ───────────
  _metadata.file_name              AS source_file_name,
  _metadata.file_path              AS source_file_path,
  _metadata.file_modification_time AS file_modified_at,
  current_timestamp()              AS ingested_at

FROM STREAM read_files(

  -- ADLS Gen2 path — Auto Loader watches this folder continuously
  'abfss://raw-data@adbeasewithdata5699.dfs.core.windows.net/incoming/orders/',

  format            => 'json',
  multiLine         => true,       -- handles pretty-printed JSON files
  schemaEvolutionMode => 'rescue'  -- unknown fields saved to _rescued_data column
                                   -- pipeline never fails on new fields
)
